### ISSUE TITLE
Flushing Appender

### ISSUE THREAD

**Issue by eyce9000** [danielwegener/logback-kafka-appender#10]
What is the best way to make sure that all messages are flushed to Kafka before a program exits?

I realize this is more of a general logback question.

**Comment by danielwegener** [comment]
Good question!
The current implementation of logback-kafka-appender uses logbacks lifecycle callbacks. Each logback component with a lifecycle will [use the producers close method](https://github.com/danielwegener/logback-kafka-appender/blob/06e026dae772558d03d1b0f1e9b247dc548dcd1c/src/main/java/com/github/danielwegener/logback/kafka/KafkaAppenderBase.java#L83). This close method will block until all messages could be sent (we could though instead add a thread that waits for a configurable timeout and will terminate after this timeout even if some messages were not sent - more or less the same could be achieved from the outside by signalling a SIGTERM and a following SIGKILL after a grace period).

The other interesting question is: Under which conditions will logback invoke the close callback - and this is indeed more like a general logback question. Since a logback-context lifecycle is not managed by a kind of container (it is rather created ad-hoc on the first `LoggerFactory.getLogger(...)` invocation), the only real possibility to recognize a shutdown would be a jvm shutdown hook. I have not found such a mechanism in logback 1.1.2, but the master branch contains some [promising progress](https://github.com/qos-ch/logback/tree/master/logback-core/src/main/java/ch/qos/logback/core/hook)

Thogh, logback shutdown hooks seem not yet to be released so you mal will need to roll your own shutdown hook that forces the logging context to stop (again waiting thread with a timeout may be useful).

Thanks for the leading question into this direction, we will investigate this further.

**Comment by danielwegener** [comment]
Update: The Kafka producer itself does only spawn daemon threads so they wont prevent the jvm from shutting down. Thus I think you will need to add a custom shutdown hook that does a graceful LoggerContext shutdown until logback supports a clean shutdown. [Example ahead](https://github.com/logstash/logstash-logback-encoder/issues/74#issuecomment-72792219).

**Comment by eyce9000** [comment]
Exactly the same thing I found. Perfect.
