### ISSUE TITLE
Order of events

### ISSUE THREAD

**Issue by mirono** [danielwegener/logback-kafka-appender#100]
We have an issue that the timestamps of the events are not chronologically ordered. This causes some events to show in Kibana before earlier events.

How can we control the event order to be the same as the order sent from the app?

BTW: the @timetamp field in the index is the problematic one. As far as I could tell the timestamp field inside the log record is ok.

**Comment by danielwegener** [comment]
This is expected. Kafka does not "reorder" messages according to a timestamp criteria but simply emits them in the order.
I do not know where your timestamp fields are coming from (this depends on the chosen formatter) but essentially it would be  the task of elasticsearch/kibana to interpret the timestamp from the kafka message instead of taking its own timestamp when the message is read from kafka (event time vs wall clock time). I think you should look somewhere at the ingest configuration of kibana.

**Comment by bobanpaul** [comment]
@danielwegener We are logging to console and kafka appender. The log event time in the console appender is same as when the event got logged(info or error was called) but the event time on the kafka appender is different; it is delayed by few seconds. Also even time of later logs can be before the earlier ones that got logged. For example if the application logs log-1->log-2-log-3->log-4->log-5 in this order , logs would show up as log-3->log-1->log-2>log-5>log-4 with reference to event time. Any help with figuring out what could be causing this and a possible fix?
